default_stages:
- commit
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=5000]
  - id: check-yaml
  - id: detect-private-key
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-toml

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.2
  hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format

- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.17
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-mkdocs
    - mdformat-admon

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.0
  hooks:
  - id: mypy

- repo: https://github.com/pdm-project/pdm
  rev: 2.15.1
  hooks:
  - id: pdm-export
    args: ["-o", "requirements.txt", "--without-hashes", "--prod"]
    files: ^pdm.lock$
  - id: pdm-lock-check
