dataset_root: /projects/kaggle/LEAP/data/
logs_root: /projects/kaggle/LEAP/logs/
train_filename: train.csv
test_filename: test.csv
ss_filename: sample_submission.csv

hydra_dir: ${logs_root}/${now:%Y-%m-%d}_${now:%H-%M-%S}

seed: 42

dataset:
  n_rows: 100_000
  train_val_split: [0.8, 0.2]
  batch_size: 128
  num_workers: 10

early_stopping:
  _target_: src.utils.EarlyStopping
  patience: 10
  delta: 0.0
  verbose: True
  on_each_epoch: False

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-3
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5

model:
  _target_: src.models.WaveNet
  inch: 6
  kernel_size: 5

trainer:
  epochs: 300
  checkpoint_dir: ${hydra_dir}

hydra:
  run:
    dir: ${hydra_dir}
  job:
    chdir: True
